#!/usr/bin/env php
<?php

$count = $argv[1] ?? null;
$mode = $count === null ? 'join' : 'split';

if ($mode == 'split') {
    $secret = rtrim(fgets(STDIN), "\r\n");
    $len = strlen($secret);
    $last = $secret;
    for ($i = 0; $i < $count - 1; $i++) {
        $part = random_bytes($len);
        echo base64_encode($part)."\n";
        $last ^= $part;
    }
    echo base64_encode($last)."\n";
    die;
}

if ($mode == 'join') {
    $secret = null;
    while(1) {
        $part = rtrim(fgets(STDIN), "\r\n");
        if (!$part) break;
        $part = base64_decode($part);
        if ($secret === null) {
            $secret = $part;
            continue;
        }
        $secret ^= $part;
    }
    echo "$secret\n";
    die;
}
